<?php

namespace PPEPharBundle\Repository;

/**
 * commercialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commercialRepository extends \Doctrine\ORM\EntityRepository
{
}
